version: "3"
services:
  php:
    build:
      context: ./docker
      args:
        - TZ=${TZ}
    volumes:
      - ./api:/work
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - php
    ports:
      - 8000:80
    volumes:
      - ./:/work
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
